### ISSUE TITLE
Modify Calorie Intake Calculator

### ISSUE THREAD

**Issue by Codipk** [ContriHUB/EAT_EASY#12]
## Description
The current calorie calculator in the EatEasy project needs to be updated to display calories and nutritional information based on the mess menu. Users should be able to select a day and the corresponding meals (breakfast, lunch, snacks, dinner) for that day, and the system should show the collective calorie count along with other nutritional details like fats, proteins, and carbohydrates.

## Why is this feature important to you?
This feature is important to provide users with an accurate understanding of their daily calorie intake and nutritional breakdown, allowing them to make informed dietary choices. It will also make the app more personalized and user-friendly.

## Current behavior
Users manually enter the food name and quantity to get the calorie count for each item.
<img width="902" alt="Screenshot 2024-10-11 at 9 52 50 AM" src="https://github.com/user-attachments/assets/812dc1b1-84a5-44cb-a2d4-23c7957d01f8">

## Expected
1. Users select a day and meals (breakfast, lunch, snacks, dinner) from the mess menu.
2. The app shows: 
    1. Total calories for each meal and the entire day.
    2. Additional nutritional details like fats, proteins, and carbohydrates.

## Additional context
You have to use Pie charts to represent all these things in one.
Alternative solutions might include providing a breakdown of individual dish calories and nutrients for more granularity.
You may consider integrating an external API or database for nutritional data if needed.

**Comment by Neelansh-20243176** [comment]
Please assign me this issue. I am willing to work on this

**Comment by Codipk** [comment]
@Neelansh-20243176 Make the assignment request from contrihub website

**Comment by priyanshi-1316** [comment]
Can you please assign this issue to me, i would be happy to work on this if it has not been assigned till now i have already sent an assignment request from the website.

**Comment by Codipk** [comment]
@Gprakhar141 , assign this issue!!! Start working on this

**Comment by Gprakhar141** [comment]
@Codipk On it.

**Comment by Gprakhar141** [comment]
@Codipk Which APIs and features are being used in this project from the Google Cloud Console???

**Comment by Codipk** [comment]
@Gprakhar141 For mail via OTP while signup

**Comment by Codipk** [comment]
Did u get the client I'd., secret and all for env

**Comment by Codipk** [comment]
https://dev.to/chandrapantachhetri/sending-emails-securely-using-node-js-nodemailer-smtp-gmail-and-oauth2-g3a you can refer this

**Comment by Gprakhar141** [comment]
Also some fields which are expected as response from nutrition api are only available via premium account.

**Comment by Gprakhar141** [comment]
> Did u get the client I'd., secret and all for env

No I haven't. Its just asking for the apis and services to enable on the Google cloud console.

**Comment by Codipk** [comment]
@Gprakhar141 u can use any other third party api I just want to measure how many calorie including fats, carbs,etc a person intake with the given amt

**Comment by Codipk** [comment]
> > Did u get the client I'd., secret and all for env
> 
> No I haven't. Its just asking for the apis and services to enable on the Google cloud console.

U can refer that  doc which I have given you

**Comment by Gprakhar141** [comment]
@Codipk I have got the Client_Id and Client_Secret from the google console website but I am not able to get the refresh_token. There is a Token_URI field on the website. Are they both the same???

**Comment by Codipk** [comment]
No it is different

**Comment by Codipk** [comment]
U can search on internet how to get these credentials

**Comment by RITIK-CHAUDHRY** [comment]
@Codipk i have sent request through contrihub website please assign thi issue to me

**Comment by Gprakhar141** [comment]
@RITIK-CHAUDHRY Hey this issue is already solved.
#18

**Comment by RITIK-CHAUDHRY** [comment]
On conrihub its showing open
Can i apply on others as there is restriction of 2

**Comment by Codipk** [comment]
This issue has been resolved by @Gprakhar141.On website we will going to update it soon.
