### ISSUE TITLE
Bug in Contact Us Form

### ISSUE THREAD

**Issue by Codipk** [ContriHUB/EAT_EASY#13]
## Expected behavior
The Contact Us form should submit the entered data correctly to the backend, and the user’s query should be stored/processed successfully.

## Current behavior
The form data is not being correctly submitted to the backend. Either incomplete or incorrect data is being received on the server-side

<img width="694" alt="Screenshot 2024-10-11 at 10 15 05 AM" src="https://github.com/user-attachments/assets/3c6c74ab-40f9-4f5e-962d-9e255228255b">
<img width="834" alt="Screenshot 2024-10-11 at 10 14 28 AM" src="https://github.com/user-attachments/assets/5853ff76-b2fa-44c2-ab63-a9cba6154da2">

## Steps to reproduce
Navigate to the Contact Us page.
Fill in all required fields (e.g., name, email, message).

Submit the form.
The feedback should be given on submitting if there is error in submitting so display that error from server end.
## Possible Solution
There may be an issue with the form data being serialized before submission or an issue in the backend API parsing the incoming data. Ensure the form is properly handling data serialization and confirm that the backend is correctly parsing the received data.

Detailed Description (screenshots, code snippets etc.)
Provide screenshots of network requests showing the form submission, along with any relevant error messages from the backend logs or API response.

**Comment by chow870** [comment]
plz assign this to me

**Comment by RavindraRinwa** [comment]
Could you please assign this issue to me? I'd be happy to take it on. Thanks!

**Comment by priyanshi-1316** [comment]
Can you please assign this issue to me , i have already sent an assignment request on the website. Thanks !!

**Comment by Codipk** [comment]
@RajatX24 assigned this task. Comment here so that I can make u assignee

**Comment by RajatX24** [comment]
Thank you for assigning. Working on it now.

**Comment by divyanshu-912** [comment]
give it to me

**Comment by RajatX24** [comment]
Hello @Codipk ,

I have made a PR for this issue.
You can check it out here: https://github.com/ContriHUB/EAT_EASY/pull/15

**Comment by Codipk** [comment]
@RajatX24 send the request for approval of PR

**Comment by RITIK-CHAUDHRY** [comment]
i have sent request through contrihub website please assign thi issue to me @Codipk
