### ISSUE TITLE
Enable Viewing of Individual Complaint Details under all complaints section

### ISSUE THREAD

**Issue by Codipk** [ContriHUB/EAT_EASY#22]
# Description
Currently, there is no functionality to view individual complaints when clicking on a complaint title. This feature would allow users to click on any complaint title and open the corresponding complaint details.

1. When a user clicks on any complaint title in the 'All Complaints' view, it should trigger an API call (already available in the complaintApi.js file) to fetch the individual complaint data.
2. The page that will be rendered after the API call will be the IndividualComplaint component/page, which is located under the warden folder.
3. The fetched data will be displayed on the IndividualComplaint page, showing the detailed information of the selected complaint.

**Comment by Vaishnavi1047** [comment]
@Codipk i have requested for it pr donot know if anyone before have made req Or not

**Comment by RITIK-CHAUDHRY** [comment]
@Codipk is it open or somebody is working on it

**Comment by Codipk** [comment]
@Vaishnavi1047 U'r assigned with this issue. Strt working!!

**Comment by RITIK-CHAUDHRY** [comment]
@Codipk  mam if someone else is working or completed please close my request on contrihub as theni can apply to other
