### ISSUE TITLE
 Add Contact Us Form

### ISSUE THREAD

**Issue by Codipk** [ContriHUB/EAT_EASY#3]
### Feature Description
Currently, the "Contact Us" page shows static contact information, which is not interactive. A contact form would enhance user engagement, allowing visitors to directly reach out with their queries, feedback, or complaints.

### Proposed Solution
Replace the existing contact information with a dynamic form where users can input their name, email address, and message. Upon submission, the form should send an email or store the message in the database for further action.

### Form Fields:

Name (Text Input)
Email (Email Input)
Message (Textarea)
<img width="1373" alt="Screenshot 2024-10-05 at 11 48 07 PM" src="https://github.com/user-attachments/assets/dbaa55fe-e4d3-4ec5-8f10-8a0ef3e47628">

Free to use Bootstrap

**Comment by chow870** [comment]
plz assign this task to me.

**Comment by anvesh-singh** [comment]
i can work on this and i also have something on my mind about the design so can you please assign this to me

**Comment by Vaishnavi1047** [comment]
@Codipk ,I have designed this before too i can work on this

**Comment by Socrii** [comment]
@Codipk, could you assign this task to me? I think I would definitely come up with a great solution.

**Comment by Codipk** [comment]
As per the rules, this task is assigned to @chow870 ,  please start working on this issue. After you complete the task, create a pull request (PR) and make sure to attach a screenshot of your work on the website to showcase what you've done.

**Comment by chow870** [comment]
@Codipk I have messaged you on discord regarding some doubts in the installation procedure

**Comment by chow870** [comment]
@Codipk I have messaged you on discord regarding the edits and Pr
