### ISSUE TITLE
Improve the UI of ALL Complaints Section

### ISSUE THREAD

**Issue by Codipk** [ContriHUB/EAT_EASY#4]
The current "All Complaints" table in the EatEasy project displays complaints in a standard tabular format. However, this layout is not visually engaging and does not encourage user interaction. Improving the UI to display complaints in a blog list or card layout with fields such as a "Read More" option would make the content more readable and appealing.

# Why is this feature important to you?
The table format lacks an interactive and modern feel. Users may find it difficult to explore or read through the complaints in depth. A blog-like or card-based design will enhance user experience and make the content more accessible.

# Expected Behaviour 
1. Display complaints as individual cards or blog lists rather than table rows.
2. Include the following fields within each card:
     1. Title
     2. Thumbnail/Picture
     3. Short description (first few lines of the complaint)
     4. Date
     5. Upvote/Downvote count
     6. Status (Resolved/Unresolved)
     7. "Read More" button to expand the full complaint.
3. Add subtle visual elements to highlight the importance or status of the complaint (e.g., color for resolved/unresolved status).

<img width="1348" alt="Screenshot 2024-10-09 at 11 44 01 AM" src="https://github.com/user-attachments/assets/ff784d47-2a69-48b2-8257-63546f05f6bf">

Please describe alternative solutions or features you have considered.

**Comment by wenayy** [comment]
assign this to me i will work on it iby EOD

**Comment by CoderFleet** [comment]
@Codipk Could you assign this issue to me
I have requested on Contrihub website

**Comment by Codipk** [comment]
@CoderFleet ,please start working on this issue. After you complete the task, create a pull request (PR) and make sure to attach a screenshot of your work on the website to showcase what you've done. Also while creating a PR follow the contrihub guidelines.

**Comment by CoderFleet** [comment]
Thankyou for assigning me..
Okay I will start working right away @Codipk

**Comment by CoderFleet** [comment]
@Codipk, what should I fill out in the PORT section of the environment file? I was trying to set up the project on my machine
![image](https://github.com/user-attachments/assets/4bca16ff-7ecb-4bf7-bbd5-9c70df24b59b)

Also, could you please share your discord username for smoother communications

**Comment by Codipk** [comment]
This port is used by backend so u can give any port like 4000 or something else which is available where your backend runs
Discord: diptikumari0337

**Comment by CoderFleet** [comment]
I have messaged you in discord 
Please Check

**Comment by Vaishnavi1047** [comment]
@Codipk I am now working on this issue

**Comment by Vaishnavi1047** [comment]
![Screenshot 2024-10-18 010729](https://github.com/user-attachments/assets/6e17c322-0763-405f-9fe5-9c1de1670fe6)
@Codipk is it fine mam?

**Comment by Codipk** [comment]
@Vaishnavi1047 I told u na card type Layout is required

**Comment by Vaishnavi1047** [comment]
Okayy will change it clss se aake

**Comment by Vaishnavi1047** [comment]
@Codipk bss orientation hi change krna h na rest the design its fine or not?

**Comment by Codipk** [comment]
@Vaishnavi1047 chk discord
