### ISSUE TITLE
Sign up using Google , and other social media.

### ISSUE THREAD

**Issue by Codipk** [ContriHUB/EAT_EASY#7]
The goal is to implement a Signup feature using Google, LinkedIn, and Twitter OAuth. This will allow new users to sign up for the platform without having to create a separate account, by using their existing credentials from Google, LinkedIn, or Twitter.
Many users prefer using their social accounts to sign up for platforms. This feature will:

Simplify the signup process.
Increase user registration by offering familiar, convenient options.
Improve security by leveraging OAuth providers for user authentication and data privacy.

The solution will involve integrating OAuth with Google, LinkedIn, and Twitter for user signup. When a user clicks on one of the social media buttons, they will be redirected to the respective OAuth provider, and after successful authentication, they will be able to create an account using the information from their social profile. 
<img width="1341" alt="Screenshot 2024-10-09 at 2 30 04 PM" src="https://github.com/user-attachments/assets/4d8ea9bf-f6b5-4679-8479-1a5f4a544518">

# Frontend:
Update the signup page with buttons for Google, LinkedIn, and Twitter.
When a user clicks one of the buttons, redirect them to the respective OAuth provider.
After successful authentication, handle the user signup process.
# Backend:
Configure OAuth strategies in Passport.js (or a similar tool) for each social media provider.
Handle token verification, extract user data, and create a new user account in the database.
After successful signup, log the user in and redirect them to the main dashboard or homepage.

**Comment by wenayy** [comment]
assign me this issue

**Comment by aachintya** [comment]
I have requested for the issue. Please check

**Comment by prashantrai-30** [comment]
Hey @Codipk ,can you assign this to me i have potential solution for this issue in my mind.

**Comment by Codipk** [comment]
@aachintya , You can start working on this issue.

**Comment by aachintya** [comment]
idk i don't have much time left but the issue i am having is that the site wants RegNo to be the unique identity for the user and ofcourse gmail id se we can't fetch that so it's problematic. How to return and what to return after making a token is an issue. The better option would be linking gmail after normal signup.

**Comment by Codipk** [comment]
@aachintya u can change the schema by doing reg field required false . I think then it would be fine ?

**Comment by aachintya** [comment]
> @aachintya u can change the schema by doing reg field required false . I think then it would be fine ?

lot of places use registration number in the codebase. it would practically make many features useless.

**Comment by Codipk** [comment]
Cann't u do it without changing the schema?and if do normal sign up then linking with Google it will be no use then ...it make no sense

**Comment by aachintya** [comment]
> Cann't u do it without changing the schema?and if do normal sign up then linking with Google it will be no use then ...it make no sense

thats understandable but i am out of time 🥹
like i need to implement it similar to the codesangam website now allowing only gmails with @mnnit.ac.in to sign up.
i guess i'll let others take this for now. If at the end if someone is not able to do it. i'll try again

**Comment by aachintya** [comment]
> Cann't u do it without changing the schema?and if do normal sign up then linking with Google it will be no use then ...it make no sense

 thats understandable but i am out of time 🥹 like i need to implement it similar to the codesangam website now allowing only gmails with @mnnit.ac.in to sign up extracting registration number from there only. i guess i'll let others take this for now. If at the end if someone is not able to do it. i'll reach out to you.

**Comment by Codipk** [comment]
@aachintya No problem!

**Comment by Codipk** [comment]
I don't want this feature so closing this issue.
